config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dishes
  end
  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :restaurants
  end
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/item.rb
class Admin::Item < ApplicationRecord
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_admin_item, only: [:show, :edit, :update, :destroy]

  # GET /admin/items
  # GET /admin/items.json
  def index
    @admin_items = Admin::Item.all
  end

  # GET /admin/items/1
  # GET /admin/items/1.json
  def show
  end

  # GET /admin/items/new
  def new
    @admin_item = Admin::Item.new
  end

  # GET /admin/items/1/edit
  def edit
  end

  # POST /admin/items
  # POST /admin/items.json
  def create
    @admin_item = Admin::Item.new(admin_item_params)

    respond_to do |format|
      if @admin_item.save
        format.html { redirect_to @admin_item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @admin_item }
      else
        format.html { render :new }
        format.json { render json: @admin_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/items/1
  # PATCH/PUT /admin/items/1.json
  def update
    respond_to do |format|
      if @admin_item.update(admin_item_params)
        format.html { redirect_to @admin_item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_item }
      else
        format.html { render :edit }
        format.json { render json: @admin_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/items/1
  # DELETE /admin/items/1.json
  def destroy
    @admin_item.destroy
    respond_to do |format|
      format.html { redirect_to admin_items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_item
      @admin_item = Admin::Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_item_params
      params.require(:admin_item).permit(:price)
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<%= form_for(admin_item) do |f| %>
  <% if admin_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_item.errors.count, "error") %> prohibited this admin_item from being saved:</h2>

      <ul>
      <% admin_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/items/edit.html.erb
<h1>Editing Admin Item</h1>

<%= render 'form', admin_item: @admin_item %>

<%= link_to 'Show', @admin_item %> |
<%= link_to 'Back', admin_items_path %>

app/views/admin/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Items</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_items.each do |admin_item| %>
      <tr>
        <td><%= admin_item.price %></td>
        <td><%= link_to 'Show', admin_item %></td>
        <td><%= link_to 'Edit', edit_admin_item_path(admin_item) %></td>
        <td><%= link_to 'Destroy', admin_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Item', new_admin_item_path %>

app/views/admin/items/new.html.erb
<h1>New Admin Item</h1>

<%= render 'form', admin_item: @admin_item %>

<%= link_to 'Back', admin_items_path %>

app/views/admin/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @admin_item.price %>
</p>

<%= link_to 'Edit', edit_admin_item_path(@admin_item) %> |
<%= link_to 'Back', admin_items_path %>