config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dishes
  end
  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :restaurants
  end
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/order.rb
class Admin::Order < ApplicationRecord
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :set_admin_order, only: [:show, :edit, :update, :destroy]

  # GET /admin/orders
  # GET /admin/orders.json
  def index
    @admin_orders = Admin::Order.all
  end

  # GET /admin/orders/1
  # GET /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Admin::Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders
  # POST /admin/orders.json
  def create
    @admin_order = Admin::Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to @admin_order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1
  # PATCH/PUT /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to @admin_order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1
  # DELETE /admin/orders/1.json
  def destroy
    @admin_order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Admin::Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_order_params
      params.require(:admin_order).permit(:date, :subtotal, :taxes, :total)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for(admin_order) do |f| %>
  <% if admin_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_order.errors.count, "error") %> prohibited this admin_order from being saved:</h2>

      <ul>
      <% admin_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :subtotal %>
    <%= f.text_field :subtotal %>
  </div>

  <div class="field">
    <%= f.label :taxes %>
    <%= f.text_field :taxes %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.text_field :total %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing Admin Order</h1>

<%= render 'form', admin_order: @admin_order %>

<%= link_to 'Show', @admin_order %> |
<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Orders</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Subtotal</th>
      <th>Taxes</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_orders.each do |admin_order| %>
      <tr>
        <td><%= admin_order.date %></td>
        <td><%= admin_order.subtotal %></td>
        <td><%= admin_order.taxes %></td>
        <td><%= admin_order.total %></td>
        <td><%= link_to 'Show', admin_order %></td>
        <td><%= link_to 'Edit', edit_admin_order_path(admin_order) %></td>
        <td><%= link_to 'Destroy', admin_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Order', new_admin_order_path %>

app/views/admin/orders/new.html.erb
<h1>New Admin Order</h1>

<%= render 'form', admin_order: @admin_order %>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @admin_order.date %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @admin_order.subtotal %>
</p>

<p>
  <strong>Taxes:</strong>
  <%= @admin_order.taxes %>
</p>

<p>
  <strong>Total:</strong>
  <%= @admin_order.total %>
</p>

<%= link_to 'Edit', edit_admin_order_path(@admin_order) %> |
<%= link_to 'Back', admin_orders_path %>