config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dishes
  end
  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :restaurants
  end
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/restaurant.rb
class Admin::Restaurant < ApplicationRecord
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :set_admin_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /admin/restaurants
  # GET /admin/restaurants.json
  def index
    @admin_restaurants = Admin::Restaurant.all
  end

  # GET /admin/restaurants/1
  # GET /admin/restaurants/1.json
  def show
  end

  # GET /admin/restaurants/new
  def new
    @admin_restaurant = Admin::Restaurant.new
  end

  # GET /admin/restaurants/1/edit
  def edit
  end

  # POST /admin/restaurants
  # POST /admin/restaurants.json
  def create
    @admin_restaurant = Admin::Restaurant.new(admin_restaurant_params)

    respond_to do |format|
      if @admin_restaurant.save
        format.html { redirect_to @admin_restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @admin_restaurant }
      else
        format.html { render :new }
        format.json { render json: @admin_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/restaurants/1
  # PATCH/PUT /admin/restaurants/1.json
  def update
    respond_to do |format|
      if @admin_restaurant.update(admin_restaurant_params)
        format.html { redirect_to @admin_restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_restaurant }
      else
        format.html { render :edit }
        format.json { render json: @admin_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/restaurants/1
  # DELETE /admin/restaurants/1.json
  def destroy
    @admin_restaurant.destroy
    respond_to do |format|
      format.html { redirect_to admin_restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_restaurant
      @admin_restaurant = Admin::Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_restaurant_params
      params.require(:admin_restaurant).permit(:name, :description, :address, :phone, :logo)
    end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<%= form_for(admin_restaurant) do |f| %>
  <% if admin_restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_restaurant.errors.count, "error") %> prohibited this admin_restaurant from being saved:</h2>

      <ul>
      <% admin_restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :logo %>
    <%= f.text_field :logo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/restaurants/edit.html.erb
<h1>Editing Admin Restaurant</h1>

<%= render 'form', admin_restaurant: @admin_restaurant %>

<%= link_to 'Show', @admin_restaurant %> |
<%= link_to 'Back', admin_restaurants_path %>

app/views/admin/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_restaurants.each do |admin_restaurant| %>
      <tr>
        <td><%= admin_restaurant.name %></td>
        <td><%= admin_restaurant.description %></td>
        <td><%= admin_restaurant.address %></td>
        <td><%= admin_restaurant.phone %></td>
        <td><%= admin_restaurant.logo %></td>
        <td><%= link_to 'Show', admin_restaurant %></td>
        <td><%= link_to 'Edit', edit_admin_restaurant_path(admin_restaurant) %></td>
        <td><%= link_to 'Destroy', admin_restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Restaurant', new_admin_restaurant_path %>

app/views/admin/restaurants/new.html.erb
<h1>New Admin Restaurant</h1>

<%= render 'form', admin_restaurant: @admin_restaurant %>

<%= link_to 'Back', admin_restaurants_path %>

app/views/admin/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_restaurant.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @admin_restaurant.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @admin_restaurant.phone %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @admin_restaurant.logo %>
</p>

<%= link_to 'Edit', edit_admin_restaurant_path(@admin_restaurant) %> |
<%= link_to 'Back', admin_restaurants_path %>