config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dishes
  end
  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :restaurants
  end
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/dish.rb
class Admin::Dish < ApplicationRecord
    has_attached_file :photo
    validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/admin/dishes_controller.rb
class Admin::DishesController < ApplicationController
  before_action :set_admin_dish, only: [:show, :edit, :update, :destroy]

  # GET /admin/dishes
  # GET /admin/dishes.json
  def index
    @admin_dishes = Admin::Dish.all
  end

  # GET /admin/dishes/1
  # GET /admin/dishes/1.json
  def show
  end

  # GET /admin/dishes/new
  def new
    @admin_dish = Admin::Dish.new
  end

  # GET /admin/dishes/1/edit
  def edit
  end

  # POST /admin/dishes
  # POST /admin/dishes.json
  def create
    @admin_dish = Admin::Dish.new(admin_dish_params)

    respond_to do |format|
      if @admin_dish.save
        format.html { redirect_to @admin_dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @admin_dish }
      else
        format.html { render :new }
        format.json { render json: @admin_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/dishes/1
  # PATCH/PUT /admin/dishes/1.json
  def update
    respond_to do |format|
      if @admin_dish.update(admin_dish_params)
        format.html { redirect_to @admin_dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_dish }
      else
        format.html { render :edit }
        format.json { render json: @admin_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/dishes/1
  # DELETE /admin/dishes/1.json
  def destroy
    @admin_dish.destroy
    respond_to do |format|
      format.html { redirect_to admin_dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_dish
      @admin_dish = Admin::Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_dish_params
      params.require(:admin_dish).permit(:dishgroup, :name, :description, :price, :photo)
    end
end

app/helpers/admin/dishes_helper.rb
module Admin::DishesHelper
end

app/views/admin/dishes/_form.html.erb
<%= form_for(admin_dish, :html => { :multipart => true }) do |f| %>
  <% if admin_dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_dish.errors.count, "error") %> prohibited this admin_dish from being saved:</h2>

      <ul>
      <% admin_dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dishgroup %>
    <%= f.text_field :dishgroup %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/dishes/edit.html.erb
<h1>Editing Admin Dish</h1>

<%= render 'form', admin_dish: @admin_dish %>

<%= link_to 'Show', @admin_dish %> |
<%= link_to 'Back', admin_dishes_path %>

app/views/admin/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Dishgroup</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_dishes.each do |admin_dish| %>
      <tr>
        <td><%= admin_dish.dishgroup %></td>
        <td><%= admin_dish.name %></td>
        <td><%= admin_dish.description %></td>
        <td><%= admin_dish.price %></td>
        <td><%= link_to 'Show', admin_dish %></td>
        <td><%= link_to 'Edit', edit_admin_dish_path(admin_dish) %></td>
        <td><%= link_to 'Destroy', admin_dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Dish', new_admin_dish_path %>

app/views/admin/dishes/new.html.erb
<h1>New Admin Dish</h1>

<%= render 'form', admin_dish: @admin_dish %>

<%= link_to 'Back', admin_dishes_path %>

app/views/admin/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dishgroup:</strong>
  <%= @admin_dish.dishgroup %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_dish.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_dish.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @admin_dish.price %>
</p>

<p>
  <b>Photo:</b>
  <%= image_tag @admin_dish.photo.url %>
</p>

<%= link_to 'Edit', edit_admin_dish_path(@admin_dish) %> |
<%= link_to 'Back', admin_dishes_path %>